// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, google, instagram, jade;

  express = require('express');

  jade = require('jade');

  instagram = require('./instagram');

  google = require('./reader');

  instagram.config({
    client_id: '5e74d68db242474daa26bc02ebdd3007',
    client_secret: 'c9017bccf8504d6e9f540850dc7ea6ba',
    redirect_uri: 'http://localhost:3000/callback'
  });

  google.config({
    redirect_uri: 'http://ogilvypi.herokuapp.com/auth',
    client_id: '1096377820701.apps.googleusercontent.com',
    client_secret: 'u_OulT_9UDPlR4VtR06lwYTc'
  });

  app = express();

  app.configure(function() {
    app.set('view engine', 'jade');
    app.set('views', "" + __dirname + "/views");
    app.set('port', process.env.PORT || 3000);
    app.use(express.bodyParser());
    app.use(express["static"](__dirname + '/public'));
    app.use(express.cookieParser());
    app.use(express.session({
      secret: "shhhhhhhhhhhhhh!"
    }));
    app.use(express.methodOverride());
    return app.use(app.router);
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', function(req, res) {
    return res.render('index', {
      title: 'Hello World!'
    });
  });

  app.get('/auth', function(req, res) {
    return instagram.auth(function(resp) {
      return res.redirect(resp);
    });
  });

  app.get('/google-auth', function(req, res) {
    return google.auth(function(resp) {
      return res.redirect(resp);
    });
  });

  app.get('/callback', function(req, res) {
    return instagram.reqAccToken(req.query.code, function(resp) {
      var access_token;
      access_token = resp;
      return console.log(access_token);
    });
  });

  app.post('/create-push', function(req, res) {
    var tag;
    tag = req.body.hash_tag;
    instagram.subscribe(tag, function(resp) {
      return console.log("ok");
    });
    return res.end();
  });

  app.post('/push', function(req, res) {
    console.log(req.body);
    return res.end();
  });

  app.get('/push', function(req, res) {
    console.log(req.query['hub.challenge']);
    return res.send(req.query['hub.challenge']);
  });

  app.listen(app.get('port'));

  console.log("Express server listening on port " + (app.get('port')));

}).call(this);
