// Generated by CoffeeScript 1.3.1
(function() {
  var Canvas, Image, fs, request;

  Canvas = require('canvas');

  Image = Canvas.Image;

  fs = require('fs');

  request = require('request');

  module.exports = {
    makeA6: function(caption, pic, date, callback) {
      var canvas, ctx;
      canvas = new Canvas(1240, 1748);
      ctx = canvas.getContext('2d');
      ctx.patternQuality = 'best';
      ctx.fillStyle = '#fff';
      ctx.fillRect(0, 0, 1240, 1748);
      return request.get({
        url: pic,
        encoding: null
      }, function(err, res, body) {
        var img, month, out, stream;
        if (err) {
          throw err;
        }
        console.log(body);
        date = new Date(parseInt(date) * 1000);
        month = date.getMonth() + 1;
        date = date.getDate().toString() + '/' + month + '/' + date.getFullYear().toString();
        img = new Image;
        img.src = body;
        ctx.drawImage(img, 75, 75, 1090, 1090);
        ctx.fillStyle = '#000';
        ctx.font = '36px sans-serif';
        ctx.fillText(caption, 100, 1240);
        ctx.fillText(date, 960, 1240);
        out = fs.createWriteStream(__dirname + '/test.jpeg');
        stream = canvas.jpegStream();
        stream.on('data', function(chunk) {
          return out.write(chunk);
        });
        return stream.on('end', function() {
          console.log("saved image");
          return callback();
        });
      });
    }
  };

}).call(this);
