// Generated by CoffeeScript 1.3.1
(function() {
  var access_token, client_id, client_secret, redirect_uri, request;

  request = require('request');

  client_id = '';

  client_secret = '';

  redirect_uri = '';

  access_token = '8247617.5e74d68.c23047f134fb431ba956391a229a179c';

  module.exports = {
    config: function(config) {
      client_id = config.client_id;
      client_secret = config.client_secret;
      return redirect_uri = config.redirect_uri;
    },
    auth: function(callback) {
      var auth_url;
      auth_url = "https://api.instagram.com/oauth/authorize/?client_id=" + client_id + "&redirect_uri=" + redirect_uri + "&response_type=code";
      return callback(auth_url);
    },
    reqAccToken: function(code, callback) {
      var params;
      params = {
        client_id: client_id,
        client_secret: client_secret,
        grant_type: 'authorization_code',
        redirect_uri: redirect_uri,
        code: code
      };
      return request.post({
        url: 'https://api.instagram.com/oauth/access_token',
        form: params
      }, function(err, res, body) {
        if (err) {
          throw err;
        }
        return callback(JSON.parse(body));
      });
    },
    getMedia: function(token, callback) {
      var params;
      params = {
        access_token: token,
        count: 1
      };
      return request.get({
        url: 'https://api.instagram.com/v1/users/self/feed',
        qs: params
      }, function(err, res, body) {
        if (err) {
          throw err;
        }
        return callback(JSON.parse(body));
      });
    },
    subscribe: function(callback) {
      var params;
      console.log("subscribe");
      params = {
        client_id: client_id,
        client_secret: client_secret,
        object: 'user',
        aspect: 'media',
        callback_url: 'http://prin.localtunnel.me/push'
      };
      console.log(params);
      return request.post({
        url: 'https://api.instagram.com/v1/subscriptions/',
        form: params
      }, function(err, res, body) {
        if (err) {
          throw err;
        }
        console.log(body);
        return callback();
      });
    },
    getSubscriptions: function(callback) {
      var params;
      params = {
        client_id: client_id,
        client_secret: client_secret
      };
      return request.get({
        url: 'https://api.instagram.com/v1/subscriptions',
        qs: params
      }, function(err, res, body) {
        return callback(JSON.parse(body));
      });
    },
    delSubscriptions: function(callback) {
      var params;
      params = {
        client_id: client_id,
        client_secret: client_secret,
        object: "all"
      };
      return request.del({
        url: 'https://api.instagram.com/v1/subscriptions',
        qs: params
      }, function(err, res, body) {
        return callback(JSON.parse(body));
      });
    }
  };

}).call(this);
