// Generated by CoffeeScript 1.3.3
(function() {
  var test;

  test = function(str) {};

  test("det man retar sig på med martin soneby är att han är snubben på en fest som snor all jävla syre fattar du väl! keep on typing, never lose hope just keep on typing and never lose hope");

}).call(this);
